version: '3.9'

services:
  robot_server:
    build: ./server
    # restart: always
    container_name: robot_server
    ports:
      - '4000:4000'
    networks:
      - backend
    working_dir: /usr/src/app/
    # command: npm run dev
    env_file:
      - .env    
    depends_on: 
      - db
  db:
    build: 
      context: .
      dockerfile: mysql.Dockerfile
    restart: always
    env_file:
      - .env         
    networks:
      backend:
        aliases:
          - database

networks:
  backend:
