version: '3.9'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile-product
    restart: always
    container_name: server
    networks:
      - backend
    working_dir: /usr/src/app/
    stdin_open: true
    tty: true  
    volumes:
    - ./server/src:/usr/src/app/src
    - ./server/prisma:/usr/src/app/prisma 
    env_file:
      - .env    
    depends_on: 
      - db
  db:
    build: 
      context: .
      dockerfile: mysql.Dockerfile
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    # volumes:
    #   - my.cnf:/etc/mysql/conf.d/my.cnf
    #   - /path/to/mysql57/data:/var/lib/mysql
    env_file:
      - .env         
    networks:
      backend:
        aliases:
          - database
  phpmyadmin:
    image: arm32v7/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend
