version: '3.9'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile-product-raspi
    restart: always
    container_name: server
    networks:
      - backend
    working_dir: /usr/src/app/
    env_file:
      - .env    
    depends_on: 
      - db
    command: npm start
  phpmyadmin:
    image: arm32v7/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend


