import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedYouAwesome {
  final List<YouAwesomeModel> results;

  AutogeneratedYouAwesome({required this.results});

  factory AutogeneratedYouAwesome.fromJson(Map<String, dynamic> json) {
    var temp = <YouAwesomeModel>[];
    if (json['results'] != null) {
      temp = <YouAwesomeModel>[];
      json['results'].forEach((v) {
        temp.add(YouAwesomeModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedYouAwesome(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['results'] = results.map((v) => v.toJson()).toList();
    return data;
  }
}

class YouAwesomeModel extends Equatable {
  final int id;
  final String name;

  YouAwesomeModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory YouAwesomeModel.fromJson(Map<String, dynamic> json) {
    return YouAwesomeModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
  
}
