import 'dart:async';
import 'package:app/data_board/index.dart';
import 'dart:convert';
import 'package:dio/dio.dart';

class DataBoardProvider {
  Future<void> loadAsync(String token) async {
    /// write from keystore/keychain
    await Future.delayed(Duration(seconds: 2));
  }

  Future<void> saveAsync(String token) async {
    /// write from keystore/keychain
    await Future.delayed(Duration(seconds: 2));
  }

  Future<AutogeneratedDataBoard> readData() async {
    try {
      var dio = Dio();
      var response = await dio.get('http://192.168.1.109:4000/dht');

      return AutogeneratedDataBoard.fromJson(response.data);
    } catch (e) {
      print(e);
      rethrow;
    }
  }

  void test(bool isError) {
    if (isError == true) {
      throw Exception('manual error');
    }
  }
}
