import 'dart:async';
import 'package:app/data_board/index.dart';
import 'package:dio/dio.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DataBoardProvider {
  Future<void> loadAsync(String token) async {
    /// write from keystore/keychain
    await Future.delayed(Duration(seconds: 2));
  }

  Future<void> saveAsync(String token) async {
    /// write from keystore/keychain
    await Future.delayed(Duration(seconds: 2));
  }

  Future<AutogeneratedDataBoard> readData() async {
    try {
      await dotenv.load(fileName: "assets/.env");
      var host = dotenv.env['BACKEND_HOST'];

      var dio = Dio();
      var response = await dio.get('http://$host/api/dht');

      return AutogeneratedDataBoard.fromJson(response.data);
    } catch (e) {
      print(e);
      rethrow;
    }
  }

  void test(bool isError) {
    if (isError == true) {
      throw Exception('manual error');
    }
  }
}
