import 'package:app/data_board/index.dart';

class DataBoardRepository {
  final DataBoardProvider _dataBoardProvider = DataBoardProvider();

  DataBoardRepository();

  Future<AutogeneratedDataBoard> readData() async {
    return _dataBoardProvider.readData();
  }

  void test(bool isError) {
    _dataBoardProvider.test(isError);
  }
}
